name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - name: Build the Docker image
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: pcsx-redux/Dockerfile
          platforms: linux/amd64,linux/arm64
          no-cache: true
